### ISSUE TITLE
Both libtiff and libtiff-original dlls are missing in the latest release

### ISSUE THREAD

**Issue by BlueAcidball** [poweredbypie/textureldr#11]
![Screenshot 2021-04-09 191630](https://user-images.githubusercontent.com/40966864/114223793-24eb9700-9968-11eb-94ae-1aaf73478017.png)

**Comment by fancythedeveloper** [comment]
Just copy them from the previous releases, or do the better thing, and use either GDDLLLoader/ModLdr or Mega Hack v6 (or really any Absolute mod).

**Comment by BlueAcidball** [comment]
Thank you!
